apiVersion: custompodautoscaler.com/v1alpha1
kind: CustomPodAutoscaler
metadata:
  name: horizontal-pod-autoscaler-example
spec:
  template:
    spec:
      containers:
      - name: horizontal-pod-autoscaler-example
        image: jthomperoo/horizontal-pod-autoscaler:latest
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  config: 
    - name: minReplicas
      value: "1"
    - name: maxReplicas
      value: "3"
    - name: metrics
      value: |
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
    - name: interval
      value: "30000"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: horizontal-pod-autoscaler-example
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - custompodautoscaler.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
